In [5]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
pd.read_csv(uri)
dados = pd.read_csv(uri)
dados.head()

   home  how_it_works  contact  bought
0     1             1        0       0
1     1             1        0       0
2     1             1        0       0
3     1             1        0       0
4     1             1        0       0

In [6]:
x= dados[["home","how_it_works","contact"]]
y= dados[["bought"]]

In [7]:
mapa = { 
    "home" : "principal",
    "how_it_works" : "como_funciona",
    "contact" : "contato",
    "bought" : "comprou"
}
dados.rename(columns = mapa)

    principal  como_funciona  contato  comprou
0           1              1        0        0
1           1              1        0        0
2           1              1        0        0
3           1              1        0        0
4           1              1        0        0
..        ...            ...      ...      ...
94          0              0        1        0
95          1              1        1        1
96          0              0        1        0
97          0              1        0        0
98          0              0        0        0

[99 rows x 4 columns]

In [8]:
mapa = { 
    "home" : "principal",
    "how_it_works" : "como_funciona",
    "contact" : "contato",
    "bought" : "comprou"
}
dados = dados.rename(columns = mapa)

In [9]:
x= dados[["principal","como_funciona","contato"]]
y= dados[["comprou"]]

x.head()

   principal  como_funciona  contato
0          1              1        0
1          1              1        0
2          1              1        0
3          1              1        0
4          1              1        0

In [10]:
dados.shape

(99, 4)

In [11]:
treino_x = x[:75]
treino_x.shape

(75, 3)

In [12]:
treino_x = x[:75]
treino_y = y[:75]
teste_x = x[75:]
teste_y = y[75:]
teste_y.shape

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

Treinaremos com 75 elementos e testaremos com 24 elementos

In [31]:
from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

C:\Users\DionizVF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LinearSVC()

In [14]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 95.83%

C:\Users\DionizVF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
from sklearn.model_selection import train_test_split

train_test_split(x, y, test_size =0.25)

[    principal  como_funciona  contato
 70          1              1        0
 42          0              1        0
 23          0              1        0
 79          1              1        0
 82          0              0        1
 ..        ...            ...      ...
 81          0              0        1
 2           1              1        0
 80          0              0        1
 93          0              0        1
 89          1              0        1

 [74 rows x 3 columns],
     principal  como_funciona  contato
 43          1              0        1
 76          0              0        1
 16          0              0        1
 32          0              0        1
 62          0              0        1
 88          0              0        1
 49          1              1        0
 98          0              0        0
 96          0              0        1
 54          1              0        1
 35          1              0        1
 73          0              0        1
 8           1              1        0
 75          0              1        0
 55          1              1        0
 72          0              0        1
 13          0              0        1
 21          0              1        0
 74          0              0        1
 97          0              1        0
 20          0              0        1
 92          1              1        0
 53          1              1        0
 27          1              0        1
 29          0              0        1,
     comprou
 70        0
 42        0
 23        0
 79        1
 82        0
 ..      ...
 81        0
 2         0
 80        0
 93        0
 89        1

 [74 rows x 1 columns],
     comprou
 43        1
 76        0
 16        0
 32        0
 62        0
 88        0
 49        0
 98        0
 96        0
 54        1
 35        1
 73        0
 8         0
 75        0
 55        0
 72        0
 13        0
 21        0
 74        0
 97        0
 20        0
 92        0
 53        0
 27        1
 29        0]

In [16]:
from sklearn.model_selection import train_test_split

treino_x, teste_x, treino_y, teste_y =train_test_split(x, y, test_size =0.25)
print(treino_x.shape)
print(teste_x.shape)

(74, 3)
(25, 3)

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 100.00%

C:\Users\DionizVF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%

C:\Users\DionizVF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [19]:
treino_y.value_counts()

comprou
0          47
1          27
dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y,
                                                         random_state = SEED, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%

C:\Users\DionizVF\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [21]:
treino_y.value_counts()

comprou
0          49
1          25
dtype: int64

In [23]:
teste_y.value_counts()

comprou
0          17
1           8
dtype: int64