Suponha que a probabilidade de um casal ter filhos com olhos azuis seja de 22%. Em 50 famílias, com 3 crianças cada uma, quantas podemos esperar que tenham dois filhos com olhos azuis?


$p$ = probabilidade de sucesso

$q = (1 - p)$ = probabilidade de fracasso

$n$ = número de eventos estudados

$k$ = número de eventos desejados que tenham sucesso

In [1]:
import pandas as pd
import numpy as np
from scipy.special import comb
from scipy.stats import binom
import statsmodels.api as sm

In [2]:
p = 0.22
p

0.22

In [3]:
q = 1 - p
q

0.78

In [4]:
n = 3
n

3

In [5]:
k = 2
k

2

In [6]:
probabilidade = binom.pmf(k, n, p)
print('%0.8f' % probabilidade)

0.11325600

In [7]:
equipes = 50 * probabilidade
equipes

5.662799999999996

In [8]:
from scipy.stats import binom

p = 0.22
n = 3
k = 2
N = 50

probabilidade = binom.pmf(k, n, p)

media = probabilidade * N

In [9]:
media

5.662799999999996

In [10]:
from scipy.special import comb

combinacoes = comb(25, 20)
probabilidade = 1 / combinacoes
print('Combinações = %d e Probabilidade = %0.15f' % (combinacoes, probabilidade))

Combinações = 53130 e Probabilidade = 0.000018821757952

In [11]:
from scipy.stats import binom

p = 1 / 2  # Probabilidade de sair COROA
n = 4      # Total de lançamentos
k = 2      # Total de sucessos (faces COROA voltada para cima)

binom.pmf(k, n, p)

0.375

In [12]:
from scipy.stats import binom

p = 1 / 6   # Probabilidade de sair o número CINCO
n = 10      # Total de lançamentos

print("{0:.2%}".format(binom.sf(2, n, p)))

22.48%

O número médio de clientes que entram em uma padaria por hora é igual a 20. Obtenha a probabilidade de, na próxima hora, entrarem exatamente 25 clientes.

In [13]:
from scipy.stats import poisson

media = 20
k = 25

probabilidade = poisson.pmf(k, media)
print('%0.8f' % probabilidade)

0.04458765

A aplicação de uma prova de estatística em um concurso apresentou um conjunto de notas normalmente distribuídas. Verificou-se que o conjunto de notas tinha média 70 e desvio padrão de 5 pontos.

Qual a probabilidade de um aluno, selecionado ao acaso, ter nota menor que 85?

In [14]:
media = 70
desvio = 5
Z = (85 - media) / desvio
Z

3.0

In [15]:
probabilidade = 0.9987

In [16]:
from scipy.stats import norm
norm.cdf(Z)

0.9986501019683699

O faturamento diário de um motorista de aplicativo segue uma distribuição aproximadamente normal, com média R$300,00 e desvio padrão igual a R$50,00. Obtenha as probabilidades de que, em um dia aleatório, o motorista ganhe:

1) Entre R$ 250,00 e R$ 350,00

2) Entre R$ 400,00 e R$ 500,00

In [17]:
media = 300
desvio = 50

Z_inferior = (250 - media) / desvio
round(Z_inferior, 2)

-1.0

In [18]:
Z_superior = (350 - media) / desvio
round(Z_superior, 2)

1.0

In [19]:
from scipy.stats import norm

media = 300
desvio_padrao = 50
Z_inferior = (400 - media) / desvio_padrao
Z_superior = (500 - media) / desvio_padrao

probabilidade = norm.cdf(Z_superior) - norm.cdf(Z_inferior)
print("{0:.2%}".format(probabilidade))

2.27%

O Inmetro verificou que as lâmpadas incandescentes da fabricante XPTO apresentam uma vida útil normalmente distribuída, com média igual a 720 dias e desvio padrão igual a 30 dias. Calcule a probabilidade de uma lâmpada, escolhida ao acaso, durar:

1) Entre 650 e 750 dias

2) Mais que 800 dias

3) Menos que 700 dias

In [20]:
from scipy.stats import norm

media = 720
desvio_padrao = 30

# Item A
Z_inferior = (650 - media) / desvio_padrao
Z_superior = (750 - media) / desvio_padrao

probabilidade = norm.cdf(Z_superior) - norm.cdf(Z_inferior)
print("{0:.2%}".format(probabilidade))

# Item B
Z = (800 - media) / desvio_padrao

probabilidade = 1 - norm.cdf(Z)
print("{0:.2%}".format(probabilidade))

# Item C
Z = (700 - media) / desvio_padrao

probabilidade = norm.cdf(Z)
print("{0:.2%}".format(probabilidade))

83.15%
0.38%
25.25%

Utilizando a tabela padronizada, ou o ferramental disponibilizado pelo Python, encontre a área sob a curva normal para os valores de Z abaixo:

1) Z < 1,96

2) Z > 2,15

3) Z < -0,78

4) Z > 0,59

In [21]:
from scipy.stats import norm

# Item A
probabilidade = norm.cdf(1.96)
print("{0:0.4f}".format(probabilidade))

# Item B
probabilidade = 1 - norm.cdf(2.15)
# ou -> probabilidade = norm.sf(2.15)
print("{0:0.4f}".format(probabilidade))

# Item C
probabilidade = norm.cdf(-0.78)
print("{0:0.4f}".format(probabilidade))

# Item D
probabilidade = 1 - norm.cdf(0.59)
# ou -> probabilidade = norm.sf(0.59)
print("{0:0.4f}".format(probabilidade))

0.9750
0.0158
0.2177
0.2776

Para estimar o valor médio gasto por cada cliente de uma grande rede de fast-food, foi selecionada uma amostra de 50 clientes.

Assumindo que o valor do desvio padrão da população seja de R$ 6,00 e que esta população se distribui normalmente, obtenha a margem de erro desta estimativa para um nível de confiança de 95%.

In [22]:
from scipy.stats import norm
import numpy as np

z = norm.ppf(0.975)
desvio_padrao = 6
n = 50

e = z * (desvio_padrao / np.sqrt(n))
print("R$ {0:0.2f}".format(e))

R$ 1.66

Uma amostra aleatória simples de 1976 itens de uma população normalmente distribuída, com desvio padrão populacional igual a 11, resultou em uma média amostral de 28.

Qual o intervalo de confiança de 90% para a média populacional?

In [23]:
from scipy.stats import norm
import numpy as np

media_amostral = 28
desvio_padrao = 11
n = 1976

norm.interval(alpha = 0.90, 
                loc = media_amostral, 
                scale = desvio_padrao / np.sqrt(n))

(27.592969951356466, 28.407030048643534)

O valor do gasto médio dos clientes de uma loja de conveniência é de R$ 45,50. Assumindo que o desvio padrão dos gastos é igual a R$ 15,00, qual deve ser o tamanho da amostra para estimarmos a média populacional com um nível de significância de 10%?

Considere que o erro máximo aceitável seja de 10%.

In [24]:
from scipy.stats import norm

media = 45.5
sigma = 15
significancia = 0.10
confianca = 1 - significancia

z = norm.ppf(0.5 + (confianca / 2))
erro_percentual = 0.10
e = media * erro_percentual

n = (z * (sigma / e)) ** 2
n.round()

29.0

Um fabricante de farinha afirma que a quantidade média de farinha nas embalagens de seu principal produto é de 500 g. Um teste de pesagem em 30 embalagens amostradas ao acaso mostrou um peso médio igual à 485 g. Estudos anteriores afirmam que a distribuição dos pesos segue uma normal e que o desvio padrão populacional é igual a 20 g. Considerando um nível de significância igual a 5%, responda as seguintes questões:

1) Qual a hipótese nula a ser testada?

2) Qual o valor da estatística de teste?

3) Qual a conclusão do teste?

In [25]:
from scipy.stats import norm
import numpy as np

media_amostra = 485
desvio_padrao = 20
media = 500
significancia = 0.05
confianca = 1 - significancia
n = 30

probabilidade = (0.5 + (confianca / 2))
z_alpha_2 = norm.ppf(probabilidade)

z = (media_amostra - media) / (desvio_padrao / np.sqrt(n))

print('z =', round(z, 4))
if(z <= -z_alpha_2 or z >= z_alpha_2):
    print('Rejeitar H0')
else:
    print('Aceitar H0')

z = -4.1079
Rejeitar H0

Considere novamente os dados do exercício anterior. Um fabricante de farinha afirma que a quantidade média de farinha nas embalagens de seu principal produto é de 500 g. Um teste de pesagem em 30 embalagens amostradas ao acaso mostrou um peso médio igual à 485 g. Estudos anteriores afirmam que a distribuição dos pesos segue uma normal e que o desvio padrão populacional é igual a 20 g. Com um nível de significância igual a 5%, teste a hipótese nula de que a média do processo é igual a 500 g e marque a alternativa que indica o p-valor do teste aplicado (considere somente 5 casas decimais).

In [26]:
from scipy.stats import norm

p_valor = 2 * (1 - norm.cdf(abs(z))) 

#ou 

#p_valor = 2 * norm.sf(abs(z))

p_valor

3.992397476904053e-05

A pizzaria Muito Queijo alega que a quantidade de queijo em suas pizzas tamanho família é de, no mínimo, 350 g. Uma amostra de 35 pizzas tamanho família revelou uma média de 330 g de queijo por pizza. O desvio padrão amostral foi de 80 g.

Assumindo alfa igual a 5% e população normalmente distribuída, seria possível discordar da alegação da pizzaria? Assinale a alternativa que apresenta a estatística de teste e a decisão correta do teste.

In [27]:
from scipy.stats import norm
import numpy as np

media_amostra = 330
desvio_padrao_amostra = 80
media = 350
significancia = 0.05
confianca = 1 - significancia
n = 35

z_alpha = norm.ppf(confianca)

z = (media_amostra - media) / (desvio_padrao_amostra / np.sqrt(n))

print('z(alpha) =', round(z_alpha, 3))
print('z =', round(z, 3))
if(z <= -z_alpha):
    print('Rejeitar H0')
else:
    print('Aceitar H0')

z(alpha) = 1.645
z = -1.479
Aceitar H0

In [28]:
dataset = {
    'Y': [670, 220, 1202, 188, 1869, 248, 477, 1294, 816, 2671, 1403, 1586, 3468, 973, 701, 5310, 10950, 2008, 9574, 28863, 6466, 4274, 6432, 1326, 1423, 3211, 2140], 
    'X': [1.59, 0.56, 2.68, 0.47, 5.2, 0.58, 1.32, 3.88, 2.11, 5.53, 2.6, 2.94, 6.62, 1.91, 1.48, 10.64, 22.39, 4.2, 21.9, 59.66, 14.22, 9.57, 14.67, 3.28, 3.49, 6.94, 6.25]
}

In [29]:
dataset = pd.DataFrame(dataset)

Y = dataset.Y
X = sm.add_constant(dataset.X)

resultado_regressao = sm.OLS(Y, X, missing='drop').fit()
resultado_regressao.params

const   -168.321156
X        481.390397
dtype: float64

In [30]:
Y = dataset.Y
X = sm.add_constant(dataset.X)

In [31]:
dataset['Y_previsto_statsmodels'] = resultado_regressao.predict()
dataset.head()

      Y     X  Y_previsto_statsmodels
0   670  1.59              597.089575
1   220  0.56              101.257466
2  1202  2.68             1121.805108
3   188  0.47               57.932331
4  1869  5.20             2334.908908

In [32]:
dataset.drop(['Y_previsto_statsmodels'], axis = 1, inplace = True)
dataset

        Y      X
0     670   1.59
1     220   0.56
2    1202   2.68
3     188   0.47
4    1869   5.20
5     248   0.58
6     477   1.32
7    1294   3.88
8     816   2.11
9    2671   5.53
10   1403   2.60
11   1586   2.94
12   3468   6.62
13    973   1.91
14    701   1.48
15   5310  10.64
16  10950  22.39
17   2008   4.20
18   9574  21.90
19  28863  59.66
20   6466  14.22
21   4274   9.57
22   6432  14.67
23   1326   3.28
24   1423   3.49
25   3211   6.94
26   2140   6.25

In [33]:
#resultado_regressao.predict([1, 2.345678])[0]

In [34]:
resultado_regressao.ssr

2764109.392491646

In [35]:
resultado_regressao.ess

858787220.4593601

In [36]:
resultado_regressao.rsquared

0.9967917066613234